/**
 * The engine must work for an organization that is not this one.
 *
 * Engine (src/, schema/) and content (constitution/, acts/) are separate; a
 * fork should replace the content and deploy without touching the code.
 */
import { test } from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { execFileSync } from 'node:child_process'
import yaml from 'js-yaml'
import { validateDocument } from '../src/validate.mjs'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const STARTER = path.join(ROOT, 'examples/starter/constitution.yaml')

test('the starter is structurally valid, and refuses to ship with its placeholder contact', () => {
  const doc = yaml.load(fs.readFileSync(STARTER, 'utf8'), { schema: yaml.CORE_SCHEMA })
  const rep = validateDocument(doc, 'examples/starter/constitution.yaml')
  const codes = rep.errors.map(e => e.code)

  // Everything structural must pass: ids, numbering, the schema itself.
  assert.deepEqual(codes.filter(c => c !== 'placeholder-url'), [],
    rep.errors.map(e => `${e.code}: ${e.message}`).join('\n'))

  // And the one thing that must NOT pass: the example contact address. Copying
  // the template and deploying without replacing it fails the build, which is
  // the entire point — the previous constitution shipped two example.com URLs
  // to production and nothing objected.
  assert.deepEqual(codes, ['placeholder-url'],
    'the starter must fail validation until its placeholder contact is replaced')
})

test('the starter demonstrates a reserved article closing a numbering gap', () => {
  const doc = yaml.load(fs.readFileSync(STARTER, 'utf8'), { schema: yaml.CORE_SCHEMA })
  const reserved = doc.articles.filter(a => a.status === 'reserved')
  assert.ok(reserved.length >= 1, 'the template should show how a gap is recorded, not closed by renumbering')
  for (const a of reserved) {
    assert.ok(a.note, 'a reserved article must say why')
    assert.equal(a.content, undefined, 'a reserved article carries no text')
  }
})

test('the starter builds standalone, with no repo content and no reconciliation banner', () => {
  const out = fs.mkdtempSync(path.join(os.tmpdir(), 'ocl-starter-'))
  try {
    execFileSync(process.execPath, [path.join(ROOT, 'src/build.mjs')], {
      cwd: ROOT,
      env: {
        ...process.env,
        CONSTITUTION_FILE: 'examples/starter/constitution.yaml',
        VERSIONS_DIR: 'examples/starter/versions',   // absent on purpose
        REGISTER_FILE: 'examples/starter/register.yaml', // absent on purpose
        OUT_DIR: path.relative(ROOT, out),
        BASE_PATH: '/',
        SITE_ORIGIN: 'https://example.org'
      },
      stdio: 'pipe'
    })

    const index = path.join(out, 'index.html')
    assert.ok(fs.existsSync(index), 'the starter must produce an index page')
    const html = fs.readFileSync(index, 'utf8')

    // Content came from the starter, not from this organization's constitution.
    assert.ok(html.includes('Example Society'), 'starter content missing')
    assert.ok(!html.includes('Service to Mankind'), 'repo content leaked into a starter build')

    // No reconciliation_state means no banner: it must not be hardcoded.
    assert.ok(!html.includes('mid-reconciliation'),
      'the reconciliation banner must come from reconciliation_state, not the template')

    // A reserved article still gets its number and heading.
    assert.ok(html.includes('id="art-4"'), 'the reserved article should still hold its number')

    // At BASE_PATH=/ the links are root-relative, not stuck under /OpenCodeLaw/.
    assert.ok(!html.includes('href="/OpenCodeLaw/'), 'base path was not honoured')
    assert.ok(/href="\/styles\/tokens\.css"/.test(html), 'assets should resolve at the configured base path')

    assert.ok(fs.existsSync(path.join(out, '404.html')))
    assert.ok(fs.existsSync(path.join(out, 'sitemap.xml')))
    assert.ok(fs.existsSync(path.join(out, '.nojekyll')))
  } finally {
    fs.rmSync(out, { recursive: true, force: true })
  }
})

test('SPEC.md regenerates identically', () => {
  const spec = path.join(ROOT, 'schema/SPEC.md')
  const before = fs.readFileSync(spec, 'utf8')
  execFileSync(process.execPath, [path.join(ROOT, 'src/gen-spec.mjs')], { cwd: ROOT, stdio: 'pipe' })
  const once = fs.readFileSync(spec, 'utf8')
  execFileSync(process.execPath, [path.join(ROOT, 'src/gen-spec.mjs')], { cwd: ROOT, stdio: 'pipe' })
  const twice = fs.readFileSync(spec, 'utf8')

  assert.equal(once, twice, 'generating SPEC.md twice must produce identical output')
  assert.equal(before, once,
    'SPEC.md on disk is stale — run `npm run spec` after changing the schema')
  assert.ok(once.includes('Generated by'), 'SPEC.md must say it is generated')
})

test('the CLI exposes validate, build and spec', () => {
  const help = execFileSync(process.execPath, [path.join(ROOT, 'src/cli.mjs'), '--help'], { encoding: 'utf8' })
  for (const cmd of ['validate', 'build', 'spec']) {
    assert.ok(help.includes(cmd), `${cmd} missing from CLI help`)
  }
  const ok = execFileSync(process.execPath,
    [path.join(ROOT, 'src/cli.mjs'), 'validate', 'examples/starter/constitution.yaml'],
    { cwd: ROOT, encoding: 'utf8' })
  assert.match(ok, /valid constitution/, 'CLI should validate the starter')
})

test('the engine holds no content and the content holds no engine', () => {
  const engineFiles = fs.readdirSync(path.join(ROOT, 'src'), { recursive: true })
    .filter(f => typeof f === 'string' && f.endsWith('.mjs'))
  for (const f of engineFiles) {
    const src = fs.readFileSync(path.join(ROOT, 'src', f), 'utf8')
    // Provision text, article titles and organization names belong in YAML.
    assert.ok(!/Service to Mankind Welfare Association/.test(src.replace(/^.*servicetomankind\.github\.io.*$/gm, '')),
      `src/${f} hardcodes the organization name; it belongs in constitution/current.yaml`)
  }
})

test('documents that quote the live constitution version stay in step with it', () => {
  // The docs quote a base_version for authors to copy. The next applied Act
  // would make them silently wrong while the suite stayed green, and an author
  // copying a stale version gets a rebase error on their first run.
  //
  // Only REAL quotes are checked. The worked example in PROPOSING.md is a
  // fictional guild at its own version, and flagging that would be wrong.
  const doc = yaml.load(fs.readFileSync(path.join(ROOT, 'constitution/current.yaml'), 'utf8'), { schema: yaml.CORE_SCHEMA })
  const current = doc.info.version

  const template = fs.readFileSync(path.join(ROOT, 'bills/TEMPLATE.yaml'), 'utf8')
  const inTemplate = template.match(/base_version:\s*"([^"]+)"/)?.[1]
  assert.equal(inTemplate, current,
    `bills/TEMPLATE.yaml quotes base_version ${inTemplate} but the constitution is at ${current}`)

  // Prose of the form "Today that is `X`" is a claim about the live document.
  for (const rel of ['process/PROPOSING.md', 'process/AMENDMENT-PROCESS.md']) {
    const file = path.join(ROOT, rel)
    if (!fs.existsSync(file)) continue
    for (const m of fs.readFileSync(file, 'utf8').matchAll(/Today that is \*?\*?`([^`]+)`/g)) {
      assert.equal(m[1], current, `${rel} says the live version is ${m[1]}; it is ${current}`)
    }
  }
})
