#!/usr/bin/env node
/**
 * Generates schema/SPEC.md from the JSON Schema.
 *
 * The documentation used to be hand-written, and drifted: the docs said the
 * root key was `OpenCodeLaw`, the specs said `openconstitution`, and the
 * renderer read `ammendments`. Anyone following the documentation produced a
 * file the renderer could not read. Generating the reference from the schema
 * makes that particular failure impossible.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const SCHEMA = path.join(ROOT, 'schema/opencodelaw-1.0.schema.json')
const OUT = path.join(ROOT, 'schema/SPEC.md')

const schema = JSON.parse(fs.readFileSync(SCHEMA, 'utf8'))

const esc = s => String(s ?? '').replace(/\|/g, '\\|').replace(/\n+/g, ' ').trim()

/** Human-readable type for a subschema, following $ref one level. */
function typeOf (s, defs) {
  if (!s) return '—'
  if (s.$ref) {
    const name = s.$ref.replace('#/$defs/', '')
    return `[${name}](#${name.toLowerCase()})`
  }
  if (s.const !== undefined) return `\`"${s.const}"\``
  if (s.enum) return s.enum.map(v => `\`${v}\``).join(' \\| ')
  if (s.oneOf) return s.oneOf.map(o => typeOf(o, defs)).join(' or ')
  if (s.type === 'array') return `array of ${typeOf(s.items, defs)}`
  if (s.type === 'object') return 'object'
  if (Array.isArray(s.type)) return s.type.map(t => `\`${t}\``).join(' \\| ')
  if (s.format) return `\`${s.type}\` (${s.format})`
  return `\`${s.type ?? 'any'}\``
}

function constraints (s) {
  const out = []
  if (s.pattern) out.push(`pattern \`${s.pattern.length > 48 ? s.pattern.slice(0, 45) + '…' : s.pattern}\``)
  if (s.minLength != null) out.push(`min length ${s.minLength}`)
  if (s.minimum != null) out.push(`min ${s.minimum}`)
  if (s.minItems != null) out.push(`min items ${s.minItems}`)
  if (s.additionalProperties === false) out.push('no extra keys')
  return out.join(', ')
}

function propTable (obj, defs) {
  const required = new Set(obj.required ?? [])
  const rows = Object.entries(obj.properties ?? {}).map(([key, sub]) => {
    const req = required.has(key) ? '**yes**' : 'no'
    const c = constraints(sub)
    return `| \`${key}\` | ${typeOf(sub, defs)} | ${req} | ${esc(sub.description)}${c ? ` <br><small>${c}</small>` : ''} |`
  })
  if (!rows.length) return '_No properties._\n'
  return ['| Key | Type | Required | Notes |', '|---|---|---|---|', ...rows].join('\n') + '\n'
}

/** Conditional rules expressed as if/then, rendered so they are not invisible. */
function conditionals (obj) {
  const all = obj.allOf ?? []
  const notes = []
  for (const rule of all) {
    if (!rule.if) continue
    const cond = Object.entries(rule.if.properties ?? {})
      .map(([k, v]) => `\`${k}\` is ${v.enum ? v.enum.map(x => `\`${x}\``).join(' or ') : `\`${v.const}\``}`)
      .join(' and ')
    const then = []
    if (rule.then?.required) then.push(`\`${rule.then.required.join('`, `')}\` becomes required`)
    for (const [k, v] of Object.entries(rule.then?.properties ?? {})) {
      if (v === false) then.push(`\`${k}\` must be absent`)
    }
    const els = []
    if (rule.else?.required) els.push(`\`${rule.else.required.join('`, `')}\` is required`)
    for (const alt of rule.else?.anyOf ?? []) {
      if (alt.required) els.push(`\`${alt.required.join('`, `')}\``)
    }
    if (cond) {
      notes.push(`- When ${cond}: ${then.join('; ') || '—'}.` +
        (els.length ? ` Otherwise ${rule.else?.anyOf ? `at least one of ${els.join(' or ')} is required` : els.join('; ')}.` : ''))
    }
  }
  return notes.length ? `\n**Conditional rules**\n\n${notes.join('\n')}\n` : ''
}

const lines = []
lines.push('<!-- Generated by `npm run spec` from schema/opencodelaw-1.0.schema.json. Do not edit by hand. -->')
lines.push('')
lines.push(`# ${schema.title}`)
lines.push('')
lines.push(esc(schema.description))
lines.push('')
lines.push(`Schema: \`${schema.$id}\``)
lines.push('')
lines.push('## Root')
lines.push('')
lines.push(propTable(schema, schema.$defs))
lines.push(conditionals(schema))

lines.push('## Definitions')
lines.push('')

for (const [name, def] of Object.entries(schema.$defs ?? {})) {
  lines.push(`### ${name}`)
  lines.push('')
  if (def.description) { lines.push(esc(def.description)); lines.push('') }
  if (def.properties) {
    lines.push(propTable(def, schema.$defs))
    lines.push(conditionals(def))
  } else {
    const c = constraints(def)
    lines.push(`Type: ${typeOf(def, schema.$defs)}${c ? ` — ${c}` : ''}`)
    lines.push('')
  }
}

lines.push('## Validation beyond the schema')
lines.push('')
lines.push('`npm run validate` enforces relational rules a JSON Schema cannot express. Each fails the build:')
lines.push('')
lines.push([
  '| Check | Rule |',
  '|---|---|',
  '| `id-duplicate` | Every provision id is unique across the document |',
  '| `id-number-mismatch` | An article id must be `art-<number>`; a section id `art-<article>-s-<number>` |',
  '| `number-gap` | Article numbering is dense from 1; a gap is legal only where a `reserved` or `omitted` entry occupies it |',
  '| `number-duplicate` | No number is used twice |',
  '| `act-reference-unresolved` | Every `amended_by`, `act.amends` and `provisions[].target` resolves |',
  '| `act-file-missing` | Every `pdf` and `source_text` exists on disk |',
  '| `sor-as-authority` | No provision cites a Statement of Objects and Reasons as its authority |',
  '| `archive-version-mismatch` | An archived file\'s `info.version` matches its filename |',
  '| `archive-status` | An archived file declares `status: superseded` |',
  '| `archive-shadows-current` | No archived version duplicates the current version |',
  '| `current-count` | Exactly one document is `current` |',
  '| `placeholder-url` | No `example.com` URL in `info` |',
  '| `anchor-unresolved` | No template links to an anchor no provision produces |'
].join('\n'))
lines.push('')

fs.writeFileSync(OUT, lines.join('\n').replace(/\n{3,}/g, '\n\n'))
console.log(`schema/SPEC.md — ${Object.keys(schema.$defs ?? {}).length} definitions, ${lines.length} lines`)
